[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "@chainlink/contracts=lib/chainlink-brownie-contracts/contracts",
  "@solmate=lib/solmate/src",
  "@devops=lib/foundry-devops/src"
]
ffi = true

fs_permissions = [
  { access = "read", path = "./broadcast" }
]



[profile.release]
optimizer = true
optimizer_runs = 200



[fuzz]
runs = 256